# Generated by Django 5.0.6 on 2024-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('platform', models.CharField(choices=[('PC', 'Personal Computer'), ('PSP', 'Play Station Portable'), ('PS', 'Play Station'), ('PS2', 'Play Station 2'), ('PS3', 'Play Station 3'), ('PS4', 'Play Station 4'), ('PS5', 'Play Station 5'), ('Xbox', 'Xbox'), ('Xbox360', 'Xbox360'), ('XboxS', 'Xbox Series S'), ('DVDp', 'DVD player'), ('StSv', 'Streaming Service')], default='PC', max_length=7, primary_key=True, serialize=False)),
                ('input_hardware', models.CharField(max_length=40)),
                ('output_hardware', models.CharField(max_length=40)),
            ],
        ),
    ]
