# Generated by Django 5.0.6 on 2024-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=20)),
                ('describtion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
